//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Fa_IR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Fa_IR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Fa_IR", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درهم امارات.
        /// </summary>
        internal static string AED {
            get {
                return ResourceManager.GetString("AED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ای الف.
        /// </summary>
        internal static string aelf {
            get {
                return ResourceManager.GetString("aelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ای اترنیتی.
        /// </summary>
        internal static string aeternity {
            get {
                return ResourceManager.GetString("aeternity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما با معرفی هر یک از دوستان خود به نبض ارز 50 امتیاز دریافت می کنید و اگر مجموع امتیازات شما به 1000 امتیاز برسد از طرف نبض ارز 100 دوج کوین دریافت خواهید کرد 
        ///
        ///کد معرف شما به صورت زیر می باشد :.
        /// </summary>
        internal static string AffiliateMessage {
            get {
                return ResourceManager.GetString("AffiliateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرفی به دوستان.
        /// </summary>
        internal static string affiliateText {
            get {
                return ResourceManager.GetString("affiliateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افغانی.
        /// </summary>
        internal static string AFN {
            get {
                return ResourceManager.GetString("AFN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایون.
        /// </summary>
        internal static string aion {
            get {
                return ResourceManager.GetString("aion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درام ارمنستان.
        /// </summary>
        internal static string AMD {
            get {
                return ResourceManager.GetString("AMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آردور.
        /// </summary>
        internal static string ardor {
            get {
                return ResourceManager.GetString("ardor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارک.
        /// </summary>
        internal static string ark {
            get {
                return ResourceManager.GetString("ark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دلار استرالیا.
        /// </summary>
        internal static string AUD {
            get {
                return ResourceManager.GetString("AUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آگور.
        /// </summary>
        internal static string augur {
            get {
                return ResourceManager.GetString("augur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منات آذربایجان.
        /// </summary>
        internal static string AZN {
            get {
                return ResourceManager.GetString("AZN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بن کور.
        /// </summary>
        internal static string bancor {
            get {
                return ResourceManager.GetString("bancor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بت.
        /// </summary>
        internal static string BasicAttentionToken {
            get {
                return ResourceManager.GetString("BasicAttentionToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دینار بحرین.
        /// </summary>
        internal static string BHD {
            get {
                return ResourceManager.GetString("BHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بایننس کوین.
        /// </summary>
        internal static string binanceCoin {
            get {
                return ResourceManager.GetString("binanceCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیت کوین.
        /// </summary>
        internal static string Bitcoin {
            get {
                return ResourceManager.GetString("Bitcoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیت کوین کش.
        /// </summary>
        internal static string BitcoinCash {
            get {
                return ResourceManager.GetString("BitcoinCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیت کوین گلد.
        /// </summary>
        internal static string BitcoinGold {
            get {
                return ResourceManager.GetString("BitcoinGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیت کور.
        /// </summary>
        internal static string bitcore {
            get {
                return ResourceManager.GetString("bitcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیت شرز.
        /// </summary>
        internal static string bitshares {
            get {
                return ResourceManager.GetString("bitshares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بایت بال.
        /// </summary>
        internal static string byteball {
            get {
                return ResourceManager.GetString("byteball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بایت کوین.
        /// </summary>
        internal static string Bytecoin {
            get {
                return ResourceManager.GetString("Bytecoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بایتوم.
        /// </summary>
        internal static string bytom {
            get {
                return ResourceManager.GetString("bytom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دلار کانادا.
        /// </summary>
        internal static string CAD {
            get {
                return ResourceManager.GetString("CAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاردانو.
        /// </summary>
        internal static string Cardano {
            get {
                return ResourceManager.GetString("Cardano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چین لینک.
        /// </summary>
        internal static string chainlink {
            get {
                return ResourceManager.GetString("chainlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرانک سوئیس.
        /// </summary>
        internal static string CHF {
            get {
                return ResourceManager.GetString("CHF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیندیکیتور.
        /// </summary>
        internal static string cindicator {
            get {
                return ResourceManager.GetString("cindicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یوان چین.
        /// </summary>
        internal static string CNY {
            get {
                return ResourceManager.GetString("CNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کریپتونکس.
        /// </summary>
        internal static string cryptonex {
            get {
                return ResourceManager.GetString("cryptonex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دش.
        /// </summary>
        internal static string Dash {
            get {
                return ResourceManager.GetString("Dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال حاضر این فرمان غیر فعال می باشد.
        /// </summary>
        internal static string deactiveMessage {
            get {
                return ResourceManager.GetString("deactiveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیکرد.
        /// </summary>
        internal static string decred {
            get {
                return ResourceManager.GetString("decred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دنت.
        /// </summary>
        internal static string dent {
            get {
                return ResourceManager.GetString("dent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دنتاکوین.
        /// </summary>
        internal static string dentacoin {
            get {
                return ResourceManager.GetString("dentacoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیجی بایت.
        /// </summary>
        internal static string digibyte {
            get {
                return ResourceManager.GetString("digibyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیجیتال کش.
        /// </summary>
        internal static string DigitalCash {
            get {
                return ResourceManager.GetString("DigitalCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیجیکسداو.
        /// </summary>
        internal static string digixdao {
            get {
                return ResourceManager.GetString("digixdao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کرون دانمارک.
        /// </summary>
        internal static string DKK {
            get {
                return ResourceManager.GetString("DKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوج کوین.
        /// </summary>
        internal static string Dogecoin {
            get {
                return ResourceManager.GetString("Dogecoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت هر دلار {0} می باشد.
        /// </summary>
        internal static string dollarMessage {
            get {
                return ResourceManager.GetString("dollarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دراگون چین.
        /// </summary>
        internal static string dragonchain {
            get {
                return ResourceManager.GetString("dragonchain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الکترونیوم.
        /// </summary>
        internal static string electroneum {
            get {
                return ResourceManager.GetString("electroneum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امرکوین.
        /// </summary>
        internal static string emercoin {
            get {
                return ResourceManager.GetString("emercoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انیگما.
        /// </summary>
        internal static string Enigma {
            get {
                return ResourceManager.GetString("Enigma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایواس.
        /// </summary>
        internal static string EOS {
            get {
                return ResourceManager.GetString("EOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتریوم.
        /// </summary>
        internal static string Ethereum {
            get {
                return ResourceManager.GetString("Ethereum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتریوم کلاسیک.
        /// </summary>
        internal static string EthereumClassic {
            get {
                return ResourceManager.GetString("EthereumClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایتوس.
        /// </summary>
        internal static string ethos {
            get {
                return ResourceManager.GetString("ethos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یورو.
        /// </summary>
        internal static string EUR {
            get {
                return ResourceManager.GetString("EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اکس پی.
        /// </summary>
        internal static string ExperiencePoints {
            get {
                return ResourceManager.GetString("ExperiencePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فکتوم.
        /// </summary>
        internal static string Factom {
            get {
                return ResourceManager.GetString("Factom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فان فیر.
        /// </summary>
        internal static string funfair {
            get {
                return ResourceManager.GetString("funfair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گیم کریدیت.
        /// </summary>
        internal static string gamecredits {
            get {
                return ResourceManager.GetString("gamecredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گس.
        /// </summary>
        internal static string gas {
            get {
                return ResourceManager.GetString("gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پوند انگلیس.
        /// </summary>
        internal static string GBP {
            get {
                return ResourceManager.GetString("GBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاری گرجستان.
        /// </summary>
        internal static string GEL {
            get {
                return ResourceManager.GetString("GEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گرم طلای 18.
        /// </summary>
        internal static string geram18 {
            get {
                return ResourceManager.GetString("geram18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گرم طلای 24.
        /// </summary>
        internal static string geram24 {
            get {
                return ResourceManager.GetString("geram24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سکه گرمی.
        /// </summary>
        internal static string gerami {
            get {
                return ResourceManager.GetString("gerami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گلم.
        /// </summary>
        internal static string Golem {
            get {
                return ResourceManager.GetString("Golem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جی ایکس شرز.
        /// </summary>
        internal static string gxshares {
            get {
                return ResourceManager.GetString("gxshares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راهنما ❓
        ///شما میتوانید با سرویس های ربات آشنا شوید 
        ///قیمت لحظه ای : این قسمت شامل سه بخش سکه و ارز ، ارزهای فیات ، ارزهای دیجیتال می باشد با مراجعه به هر بخش شما میتوانید از قیمت لحظه ای آن بخش باخبر شوید
        ///
        ///ارزهای فیات: در این قسمت با انتخاب ارز مورد نظر میتوانید قیمت لحظه ای آن را با جزئیات بیشتر ببینید  
        ///
        ///جست و جو در ربات : قسمت جست و جو به شما این امکان را میدهد که بین 100 ارز اول بازار ارزهای دیجیتال به جست و جو بپردازید و اطلاعات کافی در مورد قیمت ، رتبه ارز به دست بیاورید برای جست و جو کافی است نام [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دلار هنگ کنگ.
        /// </summary>
        internal static string HKD {
            get {
                return ResourceManager.GetString("HKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اچ شر.
        /// </summary>
        internal static string hshare {
            get {
                return ResourceManager.GetString("hshare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیکون.
        /// </summary>
        internal static string ICON {
            get {
                return ResourceManager.GetString("ICON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روپیه هند.
        /// </summary>
        internal static string INR {
            get {
                return ResourceManager.GetString("INR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آی او اس توکن.
        /// </summary>
        internal static string IOStoken {
            get {
                return ResourceManager.GetString("IOStoken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیوتا.
        /// </summary>
        internal static string IOTA {
            get {
                return ResourceManager.GetString("IOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دینار عراق.
        /// </summary>
        internal static string IQD {
            get {
                return ResourceManager.GetString("IQD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ین ژاپن.
        /// </summary>
        internal static string JPY {
            get {
                return ResourceManager.GetString("JPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کین.
        /// </summary>
        internal static string kin {
            get {
                return ResourceManager.GetString("kin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کمودو.
        /// </summary>
        internal static string komodo {
            get {
                return ResourceManager.GetString("komodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کوکوین شرز.
        /// </summary>
        internal static string kucoinshares {
            get {
                return ResourceManager.GetString("kucoinshares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دینار کویت.
        /// </summary>
        internal static string KWD {
            get {
                return ResourceManager.GetString("KWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیبر نتورک.
        /// </summary>
        internal static string KyberNetwork {
            get {
                return ResourceManager.GetString("KyberNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیسک.
        /// </summary>
        internal static string lisk {
            get {
                return ResourceManager.GetString("lisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لایت کوین.
        /// </summary>
        internal static string Litecoin {
            get {
                return ResourceManager.GetString("Litecoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوپرینگ.
        /// </summary>
        internal static string loopring {
            get {
                return ResourceManager.GetString("loopring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مید سیف کوین.
        /// </summary>
        internal static string MaidSafeCoin {
            get {
                return ResourceManager.GetString("MaidSafeCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میکر.
        /// </summary>
        internal static string maker {
            get {
                return ResourceManager.GetString("maker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیبلاک.
        /// </summary>
        internal static string medibloc {
            get {
                return ResourceManager.GetString("medibloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مثقال طلا.
        /// </summary>
        internal static string mesghal {
            get {
                return ResourceManager.GetString("mesghal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موناکوین.
        /// </summary>
        internal static string monacoin {
            get {
                return ResourceManager.GetString("monacoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مونرو.
        /// </summary>
        internal static string Monero {
            get {
                return ResourceManager.GetString("Monero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رینگیت مالزی.
        /// </summary>
        internal static string MYR {
            get {
                return ResourceManager.GetString("MYR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نبلیو.
        /// </summary>
        internal static string neblio {
            get {
                return ResourceManager.GetString("neblio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نبیولس.
        /// </summary>
        internal static string Nebulas {
            get {
                return ResourceManager.GetString("Nebulas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انیوم.
        /// </summary>
        internal static string NEM {
            get {
                return ResourceManager.GetString("NEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نئو.
        /// </summary>
        internal static string NEO {
            get {
                return ResourceManager.GetString("NEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نکسوس.
        /// </summary>
        internal static string nexus {
            get {
                return ResourceManager.GetString("nexus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نیم سکه.
        /// </summary>
        internal static string nim {
            get {
                return ResourceManager.GetString("nim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کرون نروژ.
        /// </summary>
        internal static string NOK {
            get {
                return ResourceManager.GetString("NOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ان ایکس تی.
        /// </summary>
        internal static string nxt {
            get {
                return ResourceManager.GetString("nxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دلار نیوزلند.
        /// </summary>
        internal static string NZD {
            get {
                return ResourceManager.GetString("NZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امیزگو.
        /// </summary>
        internal static string omisego {
            get {
                return ResourceManager.GetString("omisego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ریال عمان.
        /// </summary>
        internal static string OMR {
            get {
                return ResourceManager.GetString("OMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انس طلا.
        /// </summary>
        internal static string ons {
            get {
                return ResourceManager.GetString("ons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیویکس.
        /// </summary>
        internal static string pivx {
            get {
                return ResourceManager.GetString("pivx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روپیه پاکستان.
        /// </summary>
        internal static string PKR {
            get {
                return ResourceManager.GetString("PKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاپولوس.
        /// </summary>
        internal static string populous {
            get {
                return ResourceManager.GetString("populous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاور لجر.
        /// </summary>
        internal static string PowerLedger {
            get {
                return ResourceManager.GetString("PowerLedger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ریال قطر.
        /// </summary>
        internal static string QAR {
            get {
                return ResourceManager.GetString("QAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گش.
        /// </summary>
        internal static string qash {
            get {
                return ResourceManager.GetString("qash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیوتوم.
        /// </summary>
        internal static string QTUM {
            get {
                return ResourceManager.GetString("QTUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کوانت استمپ.
        /// </summary>
        internal static string Quantstamp {
            get {
                return ResourceManager.GetString("Quantstamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ریل‌بلاکز.
        /// </summary>
        internal static string raiblocks {
            get {
                return ResourceManager.GetString("raiblocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آرچین.
        /// </summary>
        internal static string rchain {
            get {
                return ResourceManager.GetString("rchain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد کوین.
        /// </summary>
        internal static string reddcoin {
            get {
                return ResourceManager.GetString("reddcoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ ثبت نام شما انجام شده است اما شما عضو کانال ما نیستید \n\n عضویت در کانال نبض ارز 👇👇 \n  🏆 @nabzearz.
        /// </summary>
        internal static string RegisterNotMmeberOfChannel {
            get {
                return ResourceManager.GetString("RegisterNotMmeberOfChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ثبت نام شما انجام شده است.
        /// </summary>
        internal static string registerOperationHasDone {
            get {
                return ResourceManager.GetString("registerOperationHasDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ریکوئست نتورک.
        /// </summary>
        internal static string RequestNetwork {
            get {
                return ResourceManager.GetString("RequestNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بررسی مجدد.
        /// </summary>
        internal static string retry {
            get {
                return ResourceManager.GetString("retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ریپل.
        /// </summary>
        internal static string Ripple {
            get {
                return ResourceManager.GetString("Ripple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ربع سکه.
        /// </summary>
        internal static string rob {
            get {
                return ResourceManager.GetString("rob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روبل روسیه.
        /// </summary>
        internal static string RUB {
            get {
                return ResourceManager.GetString("RUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سالت.
        /// </summary>
        internal static string salt {
            get {
                return ResourceManager.GetString("salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ریال عربستان.
        /// </summary>
        internal static string SAR {
            get {
                return ResourceManager.GetString("SAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کرون سوئد.
        /// </summary>
        internal static string SEK {
            get {
                return ResourceManager.GetString("SEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سکه بهار آزادی.
        /// </summary>
        internal static string sekebahar {
            get {
                return ResourceManager.GetString("sekebahar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سکه امامی.
        /// </summary>
        internal static string sekeeemami {
            get {
                return ResourceManager.GetString("sekeeemami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دلار سنگاپور.
        /// </summary>
        internal static string SGD {
            get {
                return ResourceManager.GetString("SGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیاکوین.
        /// </summary>
        internal static string siacoin {
            get {
                return ResourceManager.GetString("siacoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیرین لبز توکن.
        /// </summary>
        internal static string SIRINLABSToken {
            get {
                return ResourceManager.GetString("SIRINLABSToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسمارت کش.
        /// </summary>
        internal static string smartcash {
            get {
                return ResourceManager.GetString("smartcash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاسفانه هنوز عضو کانال ما نشده اید ;(.
        /// </summary>
        internal static string sorry {
            get {
                return ResourceManager.GetString("sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استاتوس.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استیم.
        /// </summary>
        internal static string steem {
            get {
                return ResourceManager.GetString("steem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استلار.
        /// </summary>
        internal static string Stellar {
            get {
                return ResourceManager.GetString("Stellar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت لحظه ای.
        /// </summary>
        internal static string stockPrice {
            get {
                return ResourceManager.GetString("stockPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استراتیس.
        /// </summary>
        internal static string stratis {
            get {
                return ResourceManager.GetString("stratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سابستراتیوم.
        /// </summary>
        internal static string substratum {
            get {
                return ResourceManager.GetString("substratum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نماد.
        /// </summary>
        internal static string symbol {
            get {
                return ResourceManager.GetString("symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیر سوریه.
        /// </summary>
        internal static string SYP {
            get {
                return ResourceManager.GetString("SYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیس کوین.
        /// </summary>
        internal static string syscoin {
            get {
                return ResourceManager.GetString("syscoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنکس.
        /// </summary>
        internal static string tenx {
            get {
                return ResourceManager.GetString("tenx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تتر.
        /// </summary>
        internal static string tether {
            get {
                return ResourceManager.GetString("tether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بت تایلند.
        /// </summary>
        internal static string THB {
            get {
                return ResourceManager.GetString("THB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تومان.
        /// </summary>
        internal static string TMN {
            get {
                return ResourceManager.GetString("TMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترون.
        /// </summary>
        internal static string TRON {
            get {
                return ResourceManager.GetString("TRON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیر ترکیه.
        /// </summary>
        internal static string TRY {
            get {
                return ResourceManager.GetString("TRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بررسی مجدد.
        /// </summary>
        internal static string tryagain {
            get {
                return ResourceManager.GetString("tryagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دلار.
        /// </summary>
        internal static string USD {
            get {
                return ResourceManager.GetString("USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وی چین.
        /// </summary>
        internal static string vechain {
            get {
                return ResourceManager.GetString("vechain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورج.
        /// </summary>
        internal static string Verge {
            get {
                return ResourceManager.GetString("Verge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وریتزیوم.
        /// </summary>
        internal static string veritaseum {
            get {
                return ResourceManager.GetString("veritaseum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to والتون.
        /// </summary>
        internal static string walton {
            get {
                return ResourceManager.GetString("walton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویوز.
        /// </summary>
        internal static string waves {
            get {
                return ResourceManager.GetString("waves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وکس.
        /// </summary>
        internal static string wax {
            get {
                return ResourceManager.GetString("wax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام شما با موفقیت انجام شد و از طرف #نبض_ارز ورود شما را خوش آمد میگوییم.
        /// </summary>
        internal static string welcomeMessage {
            get {
                return ResourceManager.GetString("welcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایکس پلی.
        /// </summary>
        internal static string xplay {
            get {
                return ResourceManager.GetString("xplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زد کش.
        /// </summary>
        internal static string Zcash {
            get {
                return ResourceManager.GetString("Zcash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زی کلاسیک.
        /// </summary>
        internal static string zclassic {
            get {
                return ResourceManager.GetString("zclassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زی کوین.
        /// </summary>
        internal static string ZCoin {
            get {
                return ResourceManager.GetString("ZCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیرو ایکس.
        /// </summary>
        internal static string ziroX {
            get {
                return ResourceManager.GetString("ziroX", resourceCulture);
            }
        }
    }
}
